# See https://github.com/dankgrinder/dankgrinder#getting-an-authorization-token
# for instructions on how to get a token.
#
# See https://github.com/dankgrinder/dankgrinder#enabling-discords-developer-mode
# for instructions on how to get a channel id.
#
# Detailed instructions on this config are available at
# https://github.com/dankgrinder/dankgrinder#configuration.
# Make sure you have read that as well as the frequently asked questions before
# asking for support on GitHub or Discord.

instances:
  - token: ""
    channel_id: ""
    is_master: true

shifts:
  - state: "active"
    duration:
      base: 21600
  - state: "dormant"
    duration:
      base: 32400

features:
  commands:
    beg: true
    postmeme: true
    search: true
    highlow: true
    fish: true
    hunt: true
  custom_commands:
  auto_buy:
    fishing_pole: true
    hunting_rifle: true
    laptop: true
  auto_sell:
    enable: false
    items:
      - "boar"
      - "dragon"
      - "duck"
      - "fish"
      - "deer"
      - "rabbit"
      - "skunk"
  auto_gift:
    enable: false
    items:
      - "bank"
      - "pizza"
  auto_share:
    enable: false
    maximum_balance: 8000000
    minimum_balance: 5000000
  auto_bet:
    enable: false
    priority: true
    pause_below_balance: 1000000
  auto_tidepod:
    enable: false
    buy_lifesaver_on_death: true
  balance_check:
    enable: true
    interval: 180
  log_to_file: true
  debug: false

compatibility:
  postmeme:
    - "f"
    - "r"
    - "i"
    - "c"
    - "k"
  allowed_searches:
    - "bus"
    - "coat"
    - "dresser"
    - "grass"
    - "laundromat"
    - "mailbox"
    - "pantry"
    - "pocket"
    - "shoe"
    - "sink"
  search_cancel:
    - "no"
    - "bad options"
    - "i don't want to die"
    - "stop"
    - "."
  cooldown:
    beg: 48
    search: 38
    highlow: 33
    postmeme: 63
    fish: 63
    hunt: 63
    bet: 9
    sell: 6
    gift: 26
  await_response_timeout: 4

suspicion_avoidance:
  typing:
    variation: 250
    speed: 450
  message_delay:
    base: 100
    variation: 400
